### ISSUE TITLE
Set-OutlookSignature missing

### ISSUE THREAD

**Issue by Zuldan** [electricdrop/poweradmin#1]
Hi electricdrop, where can I grab a copy of Set-OutlookSignature?

It used to be at (https://github.com/electricdrop/poweradmin/blob/master/Set-OutlookSignature.ps1) but it's gone now?

**Comment by a118n** [comment]
It was uploaded by mistake with all the internal data. I'll rewrite the script to be universal and upload it later. Thank you

**Comment by Zuldan** [comment]
Fantastic. Looking forward to the new version ;-)

**Comment by a118n** [comment]
Hello Zuldan,
I've uploaded the script back as promised.

**Comment by Zuldan** [comment]
Thank you very much!
